===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/sachin/Documents/VERTICA/dbt-vertica-3x, configfile: pytest.ini
plugins: dotenv-0.5.2
collected 1 item                                                                                                                                                                              

functional/adapter/test_basic.py F                                                                                                                                                      [100%]

========================================================================================== FAILURES ===========================================================================================
____________________________________________________________________ TestSnapshotCheckColsVertica.test_snapshot_check_cols ____________________________________________________________________

self = <adapter.test_basic.TestSnapshotCheckColsVertica object at 0x7f3c18ec9de0>, project = <dbt.tests.fixtures.project.TestProjInfo object at 0x7f3c18a9b430>

    def test_snapshot_check_cols(self, project):
        # seed command
>       results = run_dbt(["seed"])

/home/sachin/Documents/VERTICA/cenv/lib/python3.10/site-packages/dbt/tests/adapter/basic/test_snapshot_check_cols.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ['seed'], expect_pass = True

    def run_dbt(args: List[str] = None, expect_pass=True):
        # Ignore logbook warnings
        warnings.filterwarnings("ignore", category=DeprecationWarning, module="logbook")
    
        # The logger will complain about already being initialized if
        # we don't do this.
        log_manager.reset_handlers()
        if args is None:
            args = ["run"]
    
        print("\n\nInvoking dbt with {}".format(args))
        res, success = handle_and_check(args)
    
        if expect_pass is not None:
>           assert success == expect_pass, "dbt exit state did not match expected"
E           AssertionError: dbt exit state did not match expected

/home/sachin/Documents/VERTICA/cenv/lib/python3.10/site-packages/dbt/tests/util.py:76: AssertionError
------------------------------------------------------------------------------------ Captured stdout setup ------------------------------------------------------------------------------------

=== Test project_root: /tmp/pytest-of-sachin/pytest-120/project0
19:21:01  Partial parse save file not found. Starting full parse.
------------------------------------------------------------------------------------- Captured log setup --------------------------------------------------------------------------------------
INFO     default_stdout:functions.py:222 19:21:01  Partial parse save file not found. Starting full parse.
DEBUG    configured_file:functions.py:220 19:21:01.489741 [debug] [MainThread]: Acquiring new vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:01.489927 [debug] [MainThread]: Acquiring new vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:01.490133 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16664664613676808542_test_basic', identifier=None)"
DEBUG    configured_file:functions.py:220 19:21:01.496806 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:01.496999 [debug] [MainThread]: On _test: BEGIN
DEBUG    configured_file:functions.py:220 19:21:01.497119 [debug] [MainThread]: Opening a new connection, currently in state init
DEBUG    configured_file:functions.py:220 19:21:01.562091 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:01.628336 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.13 seconds
DEBUG    configured_file:functions.py:220 19:21:01.629015 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:01.629377 [debug] [MainThread]: On _test: create schema if not exists "test16664664613676808542_test_basic"
  
DEBUG    configured_file:functions.py:220 19:21:01.645098 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.02 seconds
DEBUG    configured_file:functions.py:220 19:21:01.647006 [debug] [MainThread]: On _test: COMMIT
DEBUG    configured_file:functions.py:220 19:21:01.647452 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:01.647791 [debug] [MainThread]: On _test: COMMIT
DEBUG    configured_file:functions.py:220 19:21:01.659550 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.01 seconds
DEBUG    configured_file:functions.py:220 19:21:01.660139 [debug] [MainThread]: On _test: Close
------------------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------------------


Invoking dbt with ['seed']
19:21:01  Running with dbt=1.3.0
19:21:01  Partial parse save file not found. Starting full parse.
19:21:02  Found 0 models, 0 tests, 3 snapshots, 0 analyses, 296 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
19:21:02  
19:21:02  Concurrency: 4 threads (target='default')
19:21:02  
19:21:02  1 of 2 START seed file test16664664613676808542_test_basic.added ............... [RUN]
19:21:02  2 of 2 START seed file test16664664613676808542_test_basic.base ................ [RUN]
19:21:02  2 of 2 ERROR loading seed file test16664664613676808542_test_basic.base ........ [ERROR in 0.26s]
19:21:02  1 of 2 OK loaded seed file test16664664613676808542_test_basic.added ........... [Code: None, Rows: -1, Array Size: 1 in 0.36s]
19:21:02  
19:21:02  Finished running 2 seeds in 0 hours 0 minutes and 0.68 seconds (0.68s).
19:21:02  
19:21:02  Completed with 1 error and 0 warnings:
19:21:02  
19:21:02  Database Error in seed base (seeds/base.csv)
19:21:02    Severity: ROLLBACK, Message: Object "seed_rejects" already exists, Sqlstate: 42710, Routine: outputAlreadyExistsEreport, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Commands/DDL.cpp, Line: 25505, Error Code: 4213, SQL: '/* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */          create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)   ;     -- dbt seed --              copy "VMart"."test16664664613676808542_test_basic"."base"         ("id", "name", "some_date")         from local \'/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv\'         delimiter \',\'         enclosed by \'"\'         skip 1         abort on error         rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;        '
19:21:02    compiled Code at target/run/snapshot_strategy_check_cols/seeds/base.csv
19:21:02  
19:21:02  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
-------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------
DEBUG    configured_file:functions.py:220 19:21:01.677308 [debug] [MainThread]: Connection '_test' was properly closed.
INFO     configured_file:functions.py:222 

============================== 2022-10-22 19:21:01.683365 | de4e2e3c-bc21-468a-93f7-178a795a0ee3 ==============================
19:21:01.683375 [info ] [MainThread]: Running with dbt=1.3.0
INFO     configured_std_out:functions.py:222 19:21:01  Running with dbt=1.3.0
DEBUG    configured_file:functions.py:220 19:21:01.683726 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/tmp/pytest-of-sachin/pytest-120/profile0', 'send_anonymous_usage_stats': False, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'show': False, 'which': 'seed', 'rpc_method': 'seed', 'indirect_selection': 'eager'}
DEBUG    configured_file:functions.py:220 19:21:01.683862 [debug] [MainThread]: Tracking: do not track
INFO     configured_file:functions.py:222 19:21:01.689972 [info ] [MainThread]: Partial parse save file not found. Starting full parse.
INFO     configured_std_out:functions.py:222 19:21:01  Partial parse save file not found. Starting full parse.
DEBUG    configured_file:functions.py:220 19:21:01.698538 [debug] [MainThread]: Parsing macros/materializations/configs.sql
DEBUG    configured_file:functions.py:220 19:21:01.699269 [debug] [MainThread]: Parsing macros/materializations/hooks.sql
DEBUG    configured_file:functions.py:220 19:21:01.699457 [debug] [MainThread]: Parsing macros/materializations/models/view/view.sql
DEBUG    configured_file:functions.py:220 19:21:01.703964 [debug] [MainThread]: Parsing macros/materializations/models/view/create_view_as.sql
DEBUG    configured_file:functions.py:220 19:21:01.704998 [debug] [MainThread]: Parsing macros/materializations/models/view/create_or_replace_view.sql
DEBUG    configured_file:functions.py:220 19:21:01.705620 [debug] [MainThread]: Parsing macros/materializations/models/incremental/merge.sql
DEBUG    configured_file:functions.py:220 19:21:01.708200 [debug] [MainThread]: Parsing macros/materializations/models/incremental/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.709887 [debug] [MainThread]: Parsing macros/materializations/models/incremental/incremental.sql
DEBUG    configured_file:functions.py:220 19:21:01.713650 [debug] [MainThread]: Parsing macros/materializations/models/table/create_table_as.sql
DEBUG    configured_file:functions.py:220 19:21:01.714611 [debug] [MainThread]: Parsing macros/materializations/models/table/table.sql
DEBUG    configured_file:functions.py:220 19:21:01.718343 [debug] [MainThread]: Parsing macros/materializations/snapshots/snapshot_merge.sql
DEBUG    configured_file:functions.py:220 19:21:01.719673 [debug] [MainThread]: Parsing macros/materializations/snapshots/snapshot.sql
DEBUG    configured_file:functions.py:220 19:21:01.727224 [debug] [MainThread]: Parsing macros/materializations/snapshots/strategies.sql
DEBUG    configured_file:functions.py:220 19:21:01.728717 [debug] [MainThread]: Parsing macros/materializations/snapshots/helper.sql
DEBUG    configured_file:functions.py:220 19:21:01.729063 [debug] [MainThread]: Parsing macros/materializations/seeds/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.736420 [debug] [MainThread]: Parsing macros/materializations/seeds/seed.sql
DEBUG    configured_file:functions.py:220 19:21:01.740345 [debug] [MainThread]: Parsing macros/adapters/freshness.sql
DEBUG    configured_file:functions.py:220 19:21:01.741043 [debug] [MainThread]: Parsing macros/adapters/indexes.sql
DEBUG    configured_file:functions.py:220 19:21:01.741529 [debug] [MainThread]: Parsing macros/adapters/columns.sql
DEBUG    configured_file:functions.py:220 19:21:01.743640 [debug] [MainThread]: Parsing macros/adapters/relation.sql
DEBUG    configured_file:functions.py:220 19:21:01.745393 [debug] [MainThread]: Parsing macros/adapters/metadata.sql
DEBUG    configured_file:functions.py:220 19:21:01.749466 [debug] [MainThread]: Parsing macros/adapters/schema.sql
DEBUG    configured_file:functions.py:220 19:21:01.750421 [debug] [MainThread]: Parsing macros/adapters/persist_docs.sql
DEBUG    configured_file:functions.py:220 19:21:01.751212 [debug] [MainThread]: Parsing macros/materializations/configs.sql
DEBUG    configured_file:functions.py:220 19:21:01.752739 [debug] [MainThread]: Parsing macros/materializations/hooks.sql
DEBUG    configured_file:functions.py:220 19:21:01.755307 [debug] [MainThread]: Parsing macros/materializations/models/view/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.756449 [debug] [MainThread]: Parsing macros/materializations/models/view/view.sql
DEBUG    configured_file:functions.py:220 19:21:01.759968 [debug] [MainThread]: Parsing macros/materializations/models/view/create_view_as.sql
DEBUG    configured_file:functions.py:220 19:21:01.761463 [debug] [MainThread]: Parsing macros/materializations/models/view/create_or_replace_view.sql
DEBUG    configured_file:functions.py:220 19:21:01.763578 [debug] [MainThread]: Parsing macros/materializations/models/incremental/merge.sql
DEBUG    configured_file:functions.py:220 19:21:01.773120 [debug] [MainThread]: Parsing macros/materializations/models/incremental/column_helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.778164 [debug] [MainThread]: Parsing macros/materializations/models/incremental/is_incremental.sql
DEBUG    configured_file:functions.py:220 19:21:01.779151 [debug] [MainThread]: Parsing macros/materializations/models/incremental/incremental.sql
DEBUG    configured_file:functions.py:220 19:21:01.785864 [debug] [MainThread]: Parsing macros/materializations/models/incremental/strategies.sql
DEBUG    configured_file:functions.py:220 19:21:01.790118 [debug] [MainThread]: Parsing macros/materializations/models/incremental/on_schema_change.sql
DEBUG    configured_file:functions.py:220 19:21:01.800541 [debug] [MainThread]: Parsing macros/materializations/models/table/create_table_as.sql
DEBUG    configured_file:functions.py:220 19:21:01.802765 [debug] [MainThread]: Parsing macros/materializations/models/table/table.sql
DEBUG    configured_file:functions.py:220 19:21:01.806198 [debug] [MainThread]: Parsing macros/materializations/snapshots/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.814091 [debug] [MainThread]: Parsing macros/materializations/snapshots/snapshot_merge.sql
DEBUG    configured_file:functions.py:220 19:21:01.815164 [debug] [MainThread]: Parsing macros/materializations/snapshots/snapshot.sql
DEBUG    configured_file:functions.py:220 19:21:01.822408 [debug] [MainThread]: Parsing macros/materializations/snapshots/strategies.sql
DEBUG    configured_file:functions.py:220 19:21:01.832045 [debug] [MainThread]: Parsing macros/materializations/tests/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.833149 [debug] [MainThread]: Parsing macros/materializations/tests/where_subquery.sql
DEBUG    configured_file:functions.py:220 19:21:01.834337 [debug] [MainThread]: Parsing macros/materializations/tests/test.sql
DEBUG    configured_file:functions.py:220 19:21:01.837107 [debug] [MainThread]: Parsing macros/materializations/seeds/helpers.sql
DEBUG    configured_file:functions.py:220 19:21:01.848020 [debug] [MainThread]: Parsing macros/materializations/seeds/seed.sql
DEBUG    configured_file:functions.py:220 19:21:01.852238 [debug] [MainThread]: Parsing macros/get_custom_name/get_custom_alias.sql
DEBUG    configured_file:functions.py:220 19:21:01.853307 [debug] [MainThread]: Parsing macros/get_custom_name/get_custom_database.sql
DEBUG    configured_file:functions.py:220 19:21:01.854308 [debug] [MainThread]: Parsing macros/get_custom_name/get_custom_schema.sql
DEBUG    configured_file:functions.py:220 19:21:01.855800 [debug] [MainThread]: Parsing macros/adapters/freshness.sql
DEBUG    configured_file:functions.py:220 19:21:01.857010 [debug] [MainThread]: Parsing macros/adapters/indexes.sql
DEBUG    configured_file:functions.py:220 19:21:01.858679 [debug] [MainThread]: Parsing macros/adapters/columns.sql
DEBUG    configured_file:functions.py:220 19:21:01.864759 [debug] [MainThread]: Parsing macros/adapters/relation.sql
DEBUG    configured_file:functions.py:220 19:21:01.873886 [debug] [MainThread]: Parsing macros/adapters/metadata.sql
DEBUG    configured_file:functions.py:220 19:21:01.878472 [debug] [MainThread]: Parsing macros/adapters/apply_grants.sql
DEBUG    configured_file:functions.py:220 19:21:01.886676 [debug] [MainThread]: Parsing macros/adapters/schema.sql
DEBUG    configured_file:functions.py:220 19:21:01.888159 [debug] [MainThread]: Parsing macros/adapters/timestamps.sql
DEBUG    configured_file:functions.py:220 19:21:01.890276 [debug] [MainThread]: Parsing macros/adapters/persist_docs.sql
DEBUG    configured_file:functions.py:220 19:21:01.893036 [debug] [MainThread]: Parsing macros/python_model/python.sql
DEBUG    configured_file:functions.py:220 19:21:01.897014 [debug] [MainThread]: Parsing macros/utils/replace.sql
DEBUG    configured_file:functions.py:220 19:21:01.897960 [debug] [MainThread]: Parsing macros/utils/array_concat.sql
DEBUG    configured_file:functions.py:220 19:21:01.898709 [debug] [MainThread]: Parsing macros/utils/any_value.sql
DEBUG    configured_file:functions.py:220 19:21:01.899358 [debug] [MainThread]: Parsing macros/utils/array_append.sql
DEBUG    configured_file:functions.py:220 19:21:01.900207 [debug] [MainThread]: Parsing macros/utils/array_construct.sql
DEBUG    configured_file:functions.py:220 19:21:01.901243 [debug] [MainThread]: Parsing macros/utils/concat.sql
DEBUG    configured_file:functions.py:220 19:21:01.901906 [debug] [MainThread]: Parsing macros/utils/bool_or.sql
DEBUG    configured_file:functions.py:220 19:21:01.902558 [debug] [MainThread]: Parsing macros/utils/escape_single_quotes.sql
DEBUG    configured_file:functions.py:220 19:21:01.903256 [debug] [MainThread]: Parsing macros/utils/split_part.sql
DEBUG    configured_file:functions.py:220 19:21:01.904676 [debug] [MainThread]: Parsing macros/utils/intersect.sql
DEBUG    configured_file:functions.py:220 19:21:01.905267 [debug] [MainThread]: Parsing macros/utils/dateadd.sql
DEBUG    configured_file:functions.py:220 19:21:01.906102 [debug] [MainThread]: Parsing macros/utils/right.sql
DEBUG    configured_file:functions.py:220 19:21:01.906886 [debug] [MainThread]: Parsing macros/utils/data_types.sql
DEBUG    configured_file:functions.py:220 19:21:01.910949 [debug] [MainThread]: Parsing macros/utils/literal.sql
DEBUG    configured_file:functions.py:220 19:21:01.911578 [debug] [MainThread]: Parsing macros/utils/datediff.sql
DEBUG    configured_file:functions.py:220 19:21:01.912419 [debug] [MainThread]: Parsing macros/utils/cast_bool_to_text.sql
DEBUG    configured_file:functions.py:220 19:21:01.913098 [debug] [MainThread]: Parsing macros/utils/safe_cast.sql
DEBUG    configured_file:functions.py:220 19:21:01.913943 [debug] [MainThread]: Parsing macros/utils/date_trunc.sql
DEBUG    configured_file:functions.py:220 19:21:01.914665 [debug] [MainThread]: Parsing macros/utils/listagg.sql
DEBUG    configured_file:functions.py:220 19:21:01.916195 [debug] [MainThread]: Parsing macros/utils/length.sql
DEBUG    configured_file:functions.py:220 19:21:01.917186 [debug] [MainThread]: Parsing macros/utils/except.sql
DEBUG    configured_file:functions.py:220 19:21:01.918043 [debug] [MainThread]: Parsing macros/utils/hash.sql
DEBUG    configured_file:functions.py:220 19:21:01.918889 [debug] [MainThread]: Parsing macros/utils/position.sql
DEBUG    configured_file:functions.py:220 19:21:01.919673 [debug] [MainThread]: Parsing macros/utils/last_day.sql
DEBUG    configured_file:functions.py:220 19:21:01.920908 [debug] [MainThread]: Parsing macros/generic_test_sql/accepted_values.sql
DEBUG    configured_file:functions.py:220 19:21:01.921885 [debug] [MainThread]: Parsing macros/generic_test_sql/relationships.sql
DEBUG    configured_file:functions.py:220 19:21:01.922538 [debug] [MainThread]: Parsing macros/generic_test_sql/unique.sql
DEBUG    configured_file:functions.py:220 19:21:01.923021 [debug] [MainThread]: Parsing macros/generic_test_sql/not_null.sql
DEBUG    configured_file:functions.py:220 19:21:01.923702 [debug] [MainThread]: Parsing macros/etc/statement.sql
DEBUG    configured_file:functions.py:220 19:21:01.927167 [debug] [MainThread]: Parsing macros/etc/datetime.sql
DEBUG    configured_file:functions.py:220 19:21:01.932680 [debug] [MainThread]: Parsing tests/generic/builtin.sql
INFO     configured_file:functions.py:222 19:21:02.233023 [info ] [MainThread]: Found 0 models, 0 tests, 3 snapshots, 0 analyses, 296 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
INFO     configured_std_out:functions.py:222 19:21:02  Found 0 models, 0 tests, 3 snapshots, 0 analyses, 296 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
INFO     configured_file:functions.py:222 19:21:02.234642 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
DEBUG    configured_file:functions.py:220 19:21:02.235474 [debug] [MainThread]: Acquiring new vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.236427 [debug] [ThreadPool]: Acquiring new vertica connection "list_VMart"
DEBUG    configured_file:functions.py:220 19:21:02.240400 [debug] [ThreadPool]: Using vertica connection "list_VMart"
DEBUG    configured_file:functions.py:220 19:21:02.240622 [debug] [ThreadPool]: On list_VMart: /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "connection_name": "list_VMart"} */

    select schema_name
    from v_catalog.schemata
  
DEBUG    configured_file:functions.py:220 19:21:02.240746 [debug] [ThreadPool]: Opening a new connection, currently in state init
DEBUG    configured_file:functions.py:220 19:21:02.270466 [debug] [ThreadPool]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.296140 [debug] [ThreadPool]: SQL status: Code: [Column(name='schema_name', type_code=9, display_size=128, internal_size=-1, precision=None, scale=None, null_ok=True)], Rows: -1, Array Size: 1 in 0.06 seconds
DEBUG    configured_file:functions.py:220 19:21:02.297248 [debug] [ThreadPool]: On list_VMart: Close
DEBUG    configured_file:functions.py:220 19:21:02.298747 [debug] [ThreadPool]: Acquiring new vertica connection "list_VMart_test16664664613676808542_test_basic"
DEBUG    configured_file:functions.py:220 19:21:02.303308 [debug] [ThreadPool]: Using vertica connection "list_VMart_test16664664613676808542_test_basic"
DEBUG    configured_file:functions.py:220 19:21:02.303562 [debug] [ThreadPool]: On list_VMart_test16664664613676808542_test_basic: BEGIN
DEBUG    configured_file:functions.py:220 19:21:02.303685 [debug] [ThreadPool]: Opening a new connection, currently in state closed
DEBUG    configured_file:functions.py:220 19:21:02.372533 [debug] [ThreadPool]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.382725 [debug] [ThreadPool]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.08 seconds
DEBUG    configured_file:functions.py:220 19:21:02.382991 [debug] [ThreadPool]: Using vertica connection "list_VMart_test16664664613676808542_test_basic"
DEBUG    configured_file:functions.py:220 19:21:02.383118 [debug] [ThreadPool]: On list_VMart_test16664664613676808542_test_basic: /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "connection_name": "list_VMart_test16664664613676808542_test_basic"} */
select
      'VMart' as database,
      table_name as name,
      table_schema as schema,
      'table' as type
    from v_catalog.tables
    where table_schema ilike 'test16664664613676808542_test_basic'
    union all
    select
      'VMart' as database,
      table_name as name,
      table_schema as schema,
      'view' as type
    from v_catalog.views
    where table_schema ilike 'test16664664613676808542_test_basic'
  
DEBUG    configured_file:functions.py:220 19:21:02.412265 [debug] [ThreadPool]: SQL status: Code: [Column(name='database', type_code=9, display_size=5, internal_size=-1, precision=None, scale=None, null_ok=True), Column(name='name', type_code=9, display_size=128, internal_size=-1, precision=None, scale=None, null_ok=True), Column(name='schema', type_code=9, display_size=128, internal_size=-1, precision=None, scale=None, null_ok=True), Column(name='type', type_code=9, display_size=5, internal_size=-1, precision=None, scale=None, null_ok=True)], Rows: -1, Array Size: 1 in 0.03 seconds
DEBUG    configured_file:functions.py:220 19:21:02.413252 [debug] [ThreadPool]: On list_VMart_test16664664613676808542_test_basic: ROLLBACK
DEBUG    configured_file:functions.py:220 19:21:02.423819 [debug] [ThreadPool]: On list_VMart_test16664664613676808542_test_basic: Close
DEBUG    configured_file:functions.py:220 19:21:02.424681 [debug] [MainThread]: Using vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.424978 [debug] [MainThread]: On master: BEGIN
DEBUG    configured_file:functions.py:220 19:21:02.425180 [debug] [MainThread]: Opening a new connection, currently in state init
DEBUG    configured_file:functions.py:220 19:21:02.457387 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.486726 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.06 seconds
DEBUG    configured_file:functions.py:220 19:21:02.487078 [debug] [MainThread]: On master: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.487266 [debug] [MainThread]: Using vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.487448 [debug] [MainThread]: On master: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.498544 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.01 seconds
DEBUG    configured_file:functions.py:220 19:21:02.498959 [debug] [MainThread]: On master: Close
INFO     configured_file:functions.py:222 19:21:02.499707 [info ] [MainThread]: Concurrency: 4 threads (target='default')
INFO     configured_std_out:functions.py:222 19:21:02  Concurrency: 4 threads (target='default')
INFO     configured_file:functions.py:222 19:21:02.500151 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
DEBUG    configured_file:functions.py:220 19:21:02.503600 [debug] [Thread-1 (]: Began running node seed.snapshot_strategy_check_cols.added
DEBUG    configured_file:functions.py:220 19:21:02.503823 [debug] [Thread-2 (]: Began running node seed.snapshot_strategy_check_cols.base
INFO     configured_file:functions.py:222 19:21:02.504187 [info ] [Thread-1 (]: 1 of 2 START seed file test16664664613676808542_test_basic.added ............... [RUN]
INFO     configured_std_out:functions.py:222 19:21:02  1 of 2 START seed file test16664664613676808542_test_basic.added ............... [RUN]
INFO     configured_file:functions.py:222 19:21:02.504551 [info ] [Thread-2 (]: 2 of 2 START seed file test16664664613676808542_test_basic.base ................ [RUN]
INFO     configured_std_out:functions.py:222 19:21:02  2 of 2 START seed file test16664664613676808542_test_basic.base ................ [RUN]
DEBUG    configured_file:functions.py:220 19:21:02.505494 [debug] [Thread-1 (]: Acquiring new vertica connection "seed.snapshot_strategy_check_cols.added"
DEBUG    configured_file:functions.py:220 19:21:02.506295 [debug] [Thread-2 (]: Acquiring new vertica connection "seed.snapshot_strategy_check_cols.base"
DEBUG    configured_file:functions.py:220 19:21:02.506588 [debug] [Thread-1 (]: Began compiling node seed.snapshot_strategy_check_cols.added
DEBUG    configured_file:functions.py:220 19:21:02.506838 [debug] [Thread-2 (]: Began compiling node seed.snapshot_strategy_check_cols.base
DEBUG    configured_file:functions.py:220 19:21:02.507093 [debug] [Thread-1 (]: finished collecting timing info
DEBUG    configured_file:functions.py:220 19:21:02.507332 [debug] [Thread-2 (]: finished collecting timing info
DEBUG    configured_file:functions.py:220 19:21:02.507584 [debug] [Thread-1 (]: Began executing node seed.snapshot_strategy_check_cols.added
DEBUG    configured_file:functions.py:220 19:21:02.507813 [debug] [Thread-2 (]: Began executing node seed.snapshot_strategy_check_cols.base
DEBUG    configured_file:functions.py:220 19:21:02.548769 [debug] [Thread-1 (]: Writing runtime sql for node "seed.snapshot_strategy_check_cols.added"
DEBUG    configured_file:functions.py:220 19:21:02.550443 [debug] [Thread-2 (]: Writing runtime sql for node "seed.snapshot_strategy_check_cols.base"
DEBUG    configured_file:functions.py:220 19:21:02.551376 [debug] [Thread-2 (]: Using vertica connection "seed.snapshot_strategy_check_cols.base"
DEBUG    configured_file:functions.py:220 19:21:02.551626 [debug] [Thread-1 (]: Using vertica connection "seed.snapshot_strategy_check_cols.added"
DEBUG    configured_file:functions.py:220 19:21:02.551997 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: BEGIN
DEBUG    configured_file:functions.py:220 19:21:02.552265 [debug] [Thread-1 (]: On seed.snapshot_strategy_check_cols.added: BEGIN
DEBUG    configured_file:functions.py:220 19:21:02.552507 [debug] [Thread-2 (]: Opening a new connection, currently in state init
DEBUG    configured_file:functions.py:220 19:21:02.552755 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
DEBUG    configured_file:functions.py:220 19:21:02.627303 [debug] [Thread-1 (]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.631175 [debug] [Thread-2 (]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.637610 [debug] [Thread-1 (]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.08 seconds
DEBUG    configured_file:functions.py:220 19:21:02.637893 [debug] [Thread-1 (]: Using vertica connection "seed.snapshot_strategy_check_cols.added"
DEBUG    configured_file:functions.py:220 19:21:02.638022 [debug] [Thread-1 (]: On seed.snapshot_strategy_check_cols.added: /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.added"} */

    
    create table "VMart"."test16664664613676808542_test_basic"."added" ("id" integer,"name" varchar(9),"some_date" timestamp without time zone)
  ;
    -- dbt seed --
    
        copy "VMart"."test16664664613676808542_test_basic"."added"
        ("id", "name", "some_date")
        from local '/tmp/pytest-of-sachin/pytest-120/project0/seeds/added.csv'
        delimiter ','
        enclosed by '"'
        skip 1
        abort on error
        rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;
    
  
DEBUG    configured_file:functions.py:220 19:21:02.640786 [debug] [Thread-2 (]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.09 seconds
DEBUG    configured_file:functions.py:220 19:21:02.641137 [debug] [Thread-2 (]: Using vertica connection "seed.snapshot_strategy_check_cols.base"
DEBUG    configured_file:functions.py:220 19:21:02.641351 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */

    
    create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)
  ;
    -- dbt seed --
    
        copy "VMart"."test16664664613676808542_test_basic"."base"
        ("id", "name", "some_date")
        from local '/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv'
        delimiter ','
        enclosed by '"'
        skip 1
        abort on error
        rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;
    
  
DEBUG    configured_file:functions.py:220 19:21:02.689463 [debug] [Thread-1 (]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.05 seconds
DEBUG    configured_file:functions.py:220 19:21:02.702163 [debug] [Thread-1 (]: On seed.snapshot_strategy_check_cols.added: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.702442 [debug] [Thread-2 (]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.06 seconds
DEBUG    configured_file:functions.py:220 19:21:02.702737 [debug] [Thread-1 (]: Using vertica connection "seed.snapshot_strategy_check_cols.added"
DEBUG    configured_file:functions.py:220 19:21:02.704076 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.704306 [debug] [Thread-1 (]: On seed.snapshot_strategy_check_cols.added: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.704600 [debug] [Thread-2 (]: Using vertica connection "seed.snapshot_strategy_check_cols.base"
DEBUG    configured_file:functions.py:220 19:21:02.705097 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.754373 [debug] [Thread-2 (]: vertica adapter: :P Database error: Severity: ROLLBACK, Message: Object "seed_rejects" already exists, Sqlstate: 42710, Routine: outputAlreadyExistsEreport, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Commands/DDL.cpp, Line: 25505, Error Code: 4213, SQL: '/* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */          create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)   ;     -- dbt seed --              copy "VMart"."test16664664613676808542_test_basic"."base"         ("id", "name", "some_date")         from local \'/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv\'         delimiter \',\'         enclosed by \'"\'         skip 1         abort on error         rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;        '
DEBUG    configured_file:functions.py:220 19:21:02.754662 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: ROLLBACK
DEBUG    configured_file:functions.py:220 19:21:02.763790 [debug] [Thread-2 (]: On seed.snapshot_strategy_check_cols.base: Close
DEBUG    configured_file:functions.py:220 19:21:02.764169 [debug] [Thread-2 (]: finished collecting timing info
DEBUG    configured_file:functions.py:220 19:21:02.764593 [debug] [Thread-2 (]: Database Error in seed base (seeds/base.csv)
  Severity: ROLLBACK, Message: Object "seed_rejects" already exists, Sqlstate: 42710, Routine: outputAlreadyExistsEreport, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Commands/DDL.cpp, Line: 25505, Error Code: 4213, SQL: '/* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */          create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)   ;     -- dbt seed --              copy "VMart"."test16664664613676808542_test_basic"."base"         ("id", "name", "some_date")         from local \'/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv\'         delimiter \',\'         enclosed by \'"\'         skip 1         abort on error         rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;        '
  compiled Code at target/run/snapshot_strategy_check_cols/seeds/base.csv
ERROR    configured_file:functions.py:226 19:21:02.764826 [error] [Thread-2 (]: 2 of 2 ERROR loading seed file test16664664613676808542_test_basic.base ........ [ERROR in 0.26s]
ERROR    configured_std_out:functions.py:226 19:21:02  2 of 2 ERROR loading seed file test16664664613676808542_test_basic.base ........ [ERROR in 0.26s]
DEBUG    configured_file:functions.py:220 19:21:02.765202 [debug] [Thread-2 (]: Finished running node seed.snapshot_strategy_check_cols.base
DEBUG    configured_file:functions.py:220 19:21:02.858035 [debug] [Thread-1 (]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.15 seconds
DEBUG    configured_file:functions.py:220 19:21:02.859224 [debug] [Thread-1 (]: finished collecting timing info
DEBUG    configured_file:functions.py:220 19:21:02.859647 [debug] [Thread-1 (]: On seed.snapshot_strategy_check_cols.added: Close
INFO     configured_file:functions.py:222 19:21:02.860914 [info ] [Thread-1 (]: 1 of 2 OK loaded seed file test16664664613676808542_test_basic.added ........... [Code: None, Rows: -1, Array Size: 1 in 0.36s]
INFO     configured_std_out:functions.py:222 19:21:02  1 of 2 OK loaded seed file test16664664613676808542_test_basic.added ........... [Code: None, Rows: -1, Array Size: 1 in 0.36s]
DEBUG    configured_file:functions.py:220 19:21:02.861800 [debug] [Thread-1 (]: Finished running node seed.snapshot_strategy_check_cols.added
DEBUG    configured_file:functions.py:220 19:21:02.864189 [debug] [MainThread]: Acquiring new vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.864679 [debug] [MainThread]: Using vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.865009 [debug] [MainThread]: On master: BEGIN
DEBUG    configured_file:functions.py:220 19:21:02.865310 [debug] [MainThread]: Opening a new connection, currently in state closed
DEBUG    configured_file:functions.py:220 19:21:02.896126 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:02.907872 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.04 seconds
DEBUG    configured_file:functions.py:220 19:21:02.908467 [debug] [MainThread]: On master: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.908878 [debug] [MainThread]: Using vertica connection "master"
DEBUG    configured_file:functions.py:220 19:21:02.909229 [debug] [MainThread]: On master: COMMIT
DEBUG    configured_file:functions.py:220 19:21:02.918189 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.01 seconds
DEBUG    configured_file:functions.py:220 19:21:02.918804 [debug] [MainThread]: On master: Close
INFO     configured_file:functions.py:222 19:21:02.920027 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
INFO     configured_file:functions.py:222 19:21:02.920736 [info ] [MainThread]: Finished running 2 seeds in 0 hours 0 minutes and 0.68 seconds (0.68s).
INFO     configured_std_out:functions.py:222 19:21:02  Finished running 2 seeds in 0 hours 0 minutes and 0.68 seconds (0.68s).
DEBUG    configured_file:functions.py:220 19:21:02.921324 [debug] [MainThread]: Connection 'master' was properly closed.
DEBUG    configured_file:functions.py:220 19:21:02.921629 [debug] [MainThread]: Connection 'seed.snapshot_strategy_check_cols.added' was properly closed.
DEBUG    configured_file:functions.py:220 19:21:02.921925 [debug] [MainThread]: Connection 'seed.snapshot_strategy_check_cols.base' was properly closed.
INFO     configured_file:functions.py:222 19:21:02.932858 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
INFO     configured_file:functions.py:222 19:21:02.933389 [info ] [MainThread]: Completed with 1 error and 0 warnings:
INFO     configured_std_out:functions.py:222 19:21:02  Completed with 1 error and 0 warnings:
INFO     configured_file:functions.py:222 19:21:02.933782 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
ERROR    configured_file:functions.py:226 19:21:02.934116 [error] [MainThread]: Database Error in seed base (seeds/base.csv)
ERROR    configured_std_out:functions.py:226 19:21:02  Database Error in seed base (seeds/base.csv)
ERROR    configured_file:functions.py:226 19:21:02.934438 [error] [MainThread]:   Severity: ROLLBACK, Message: Object "seed_rejects" already exists, Sqlstate: 42710, Routine: outputAlreadyExistsEreport, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Commands/DDL.cpp, Line: 25505, Error Code: 4213, SQL: '/* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */          create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)   ;     -- dbt seed --              copy "VMart"."test16664664613676808542_test_basic"."base"         ("id", "name", "some_date")         from local \'/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv\'         delimiter \',\'         enclosed by \'"\'         skip 1         abort on error         rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;        '
ERROR    configured_std_out:functions.py:226 19:21:02    Severity: ROLLBACK, Message: Object "seed_rejects" already exists, Sqlstate: 42710, Routine: outputAlreadyExistsEreport, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Commands/DDL.cpp, Line: 25505, Error Code: 4213, SQL: '/* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "node_id": "seed.snapshot_strategy_check_cols.base"} */          create table "VMart"."test16664664613676808542_test_basic"."base" ("id" integer,"name" varchar(8),"some_date" timestamp without time zone)   ;     -- dbt seed --              copy "VMart"."test16664664613676808542_test_basic"."base"         ("id", "name", "some_date")         from local \'/tmp/pytest-of-sachin/pytest-120/project0/seeds/base.csv\'         delimiter \',\'         enclosed by \'"\'         skip 1         abort on error         rejected data as table "VMart"."test16664664613676808542_test_basic".seed_rejects;        '
ERROR    configured_file:functions.py:226 19:21:02.934790 [error] [MainThread]:   compiled Code at target/run/snapshot_strategy_check_cols/seeds/base.csv
ERROR    configured_std_out:functions.py:226 19:21:02    compiled Code at target/run/snapshot_strategy_check_cols/seeds/base.csv
INFO     configured_file:functions.py:222 19:21:02.935054 [info ] [MainThread]: 
INFO     configured_std_out:functions.py:222 19:21:02  
INFO     configured_file:functions.py:222 19:21:02.935285 [info ] [MainThread]: Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
INFO     configured_std_out:functions.py:222 19:21:02  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
DEBUG    configured_file:functions.py:220 19:21:02.935589 [debug] [MainThread]: Flushing usage events
------------------------------------------------------------------------------------ Captured log teardown ------------------------------------------------------------------------------------
DEBUG    configured_file:functions.py:220 19:21:03.018676 [debug] [MainThread]: Acquiring new vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:03.019028 [debug] [MainThread]: Dropping schema "_ReferenceKey(database='vmart', schema='test16664664613676808542_test_basic', identifier=None)".
DEBUG    configured_file:functions.py:220 19:21:03.022767 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:03.023010 [debug] [MainThread]: On _test: BEGIN
DEBUG    configured_file:functions.py:220 19:21:03.023134 [debug] [MainThread]: Opening a new connection, currently in state init
DEBUG    configured_file:functions.py:220 19:21:03.051652 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
DEBUG    configured_file:functions.py:220 19:21:03.059844 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.04 seconds
DEBUG    configured_file:functions.py:220 19:21:03.060111 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:03.060244 [debug] [MainThread]: On _test: /* {"app": "dbt", "dbt_version": "1.3.0", "profile_name": "test", "target_name": "default", "connection_name": "_test"} */
drop schema if exists "test16664664613676808542_test_basic" cascade
  
DEBUG    configured_file:functions.py:220 19:21:03.104119 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.04 seconds
DEBUG    configured_file:functions.py:220 19:21:03.106014 [debug] [MainThread]: On _test: COMMIT
DEBUG    configured_file:functions.py:220 19:21:03.106467 [debug] [MainThread]: Using vertica connection "_test"
DEBUG    configured_file:functions.py:220 19:21:03.106823 [debug] [MainThread]: On _test: COMMIT
DEBUG    configured_file:functions.py:220 19:21:03.120185 [debug] [MainThread]: SQL status: Code: None, Rows: -1, Array Size: 1 in 0.01 seconds
DEBUG    configured_file:functions.py:220 19:21:03.120881 [debug] [MainThread]: On _test: Close
DEBUG    configured_file:functions.py:220 19:21:03.122640 [debug] [MainThread]: Connection '_test' was properly closed.
=================================================================================== short test summary info ===================================================================================
FAILED functional/adapter/test_basic.py::TestSnapshotCheckColsVertica::test_snapshot_check_cols - AssertionError: dbt exit state did not match expected
====================================================================================== 1 failed in 1.96s =======================================================================