[0m08:14:43.280440 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:14:43.280615 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:14:43.280807 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16658216830070283515_test_connections', identifier=None)"
[0m08:14:43.282106 [debug] [MainThread]: Using vertica connection "_test"
[0m08:14:43.282267 [debug] [MainThread]: On _test: BEGIN
[0m08:14:43.282374 [debug] [MainThread]: Opening a new connection, currently in state init
[0m08:14:43.315813 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
[0m08:14:43.316066 [debug] [MainThread]: vertica adapter: :P Error: local variable 'exc' referenced before assignment
[0m08:14:43.316207 [debug] [MainThread]: On _test: Close
[0m08:14:43.316488 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  local variable 'exc' referenced before assignment
[0m08:14:43.470571 [debug] [MainThread]: Connection '_test' was properly closed.
